module.exports = [
    {
        // _id: 'QIWOejnaknafu377',
        memberId: '607114bde688ab3770b2590f',
        name: 'Bohr',
        profile: 'bohr',
        subject: 'What is real?',
        content: 'Everything we call real is made of things that cannot be regarded as real.',
        createdOn: '21 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'uWa3If7anOnj7Qke',
        memberId: '607114bde688ab3770b2590c',
        name: 'Frieza',
        profile: 'frieza',
        subject: 'I am mighty and you are not!',
        content: 'I divided by 0 once and it destroyed the planet.',
        createdOn: '21 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: 'QnaOnafeuj7kI3W7',
        memberId: '607114bde688ab3770b25909',
        name: 'Paddy',
        profile: 'andean',
        subject: 'I am mighty and you are not!',
        content: 'I\'m only a bear and I know that this is not possible. Frieza is not smart.',
        replyTo: 'uWa3If7anOnj7Qke',
        replyToOrigin: 'uWa3If7anOnj7Qke',
        createdOn: '21 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: '7eO3Wan7jaIfukQn',
        memberId: '607114bde688ab3770b2590e',
        name: 'Feynman',
        profile: 'feynman',
        subject: '',
        content: 'Nature uses only the longest threads to weave her patterns, so that each small piece of her fabric reveals the organization of the entire tapestry.',
        createdOn: '21 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'WaQ7eIk7unnOa3fj',
        memberId: '607114bde688ab3770b25906',
        name: 'Sepheroth',
        profile: 'sepheroth',
        replyTo: '7eO3Wan7jaIfukQn',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        subject: '',
        content: 'Nature gave me the longest sword that I will use to chop down cherry trees.',
        createdOn: '21 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, 
]
