module.exports = [
    {
        // _id: 'QIWOejnaknafu377',
        memberId: '604ed80ed1db6302fb00579d',
        commenterName: 'Maddy',
        commenterProfile: 'maddy',
        subject: 'Welcome to the Big Bear Book Club',
        content: 'We welcome all our readers to come snuggle up and read a bedtime story. Bears, squerrels, beavers, raccoons, whatever. All are welcome in the Big Bear Book Club. And just for good measuer - Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos voluptatum nesciunt atque fuga quam ut, deserunt, iusto adipisci nihil repellat dicta amet vitae quia recusandae laudantium soluta praesentium aut necessitatibus.',
        created: '07 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'uWa3If7anOnj7Qke',
        memberId: '604edd64e2ad40f8bd455624',
        commenterName: 'Jimbo',
        commenterProfile: 'jimbo',
        subject: 'new books',
        content: 'I\'m adding Brown Bear, Brown Bear. Goldilocks is banned',
        created: '07 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: 'QnaOnafeuj7kI3W7',
        memberId: '605039365e6e8834ebceb5f7',
        commenterName: 'Sefinaz',
        commenterProfile: 'sun',
        subject: 'new books',
        content: 'But I like Goldilocks!',
        replyTo: 'uWa3If7anOnj7Qke',
        replyToOrigin: 'uWa3If7anOnj7Qke',
        created: '07 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: 'WIunan7e7kf3OjaQ',
        memberId: '604edd64e2ad40f8bd455624',
        commenterName: 'Jimbo',
        commenterProfile: 'jimbo',
        subject: 'new books',
        replyTo: 'QnaOnafeuj7kI3W7',
        replyToOrigin: 'uWa3If7anOnj7Qke',
        content: 'Okay. I\'ll allow Goldilocks for your sandwich.',
        created: '07 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: 'eQ73kjf7IWOannu',
        memberId: '605039365e6e8834ebceb5f7',
        commenterName: 'Sefinaz',
        commenterProfile: 'sun',
        subject: 'new books',
        replyTo: 'WIunan7e7kf3OjaQ',
        replyToOrigin: 'uWa3If7anOnj7Qke',
        content: 'okay',
        created: '07 MAY 2021',
        color: '#f7fff7',
        border: '#d7ddd7',
    }, {
        // _id: '7eO3Wan7jaIfukQn',
        memberId: '605025c45e6e8834ebceb5f1',
        commenterName: 'Mekong',
        commenterProfile: 'mekong',
        subject: 'Desmond the Moon Bear',
        content: 'I\'m adding Desmond the Moon Bear',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'WaQ7eIk7unnOa3fj',
        memberId: '604ed80ed1db6302fb00579d',
        commenterName: 'Maddy',
        commenterProfile: 'maddy',
        replyTo: '7eO3Wan7jaIfukQn',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        subject: 'Desmond the Moon Bear',
        content: 'Isn\'t that a cartoon?',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'nf7nOek7uIaaQWj3',
        memberId: '605025c45e6e8834ebceb5f1',
        commenterName: 'Mekong',
        commenterProfile: 'mekong',
        subject: 'Desmond the Moon Bear',
        replyTo: 'WaQ7eIk7unnOa3fj',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        content: 'Yep',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'ek7I3nWun7jafQOa',
        memberId: '605039365e6e8834ebceb5f7',
        commenterName: 'Sefinaz',
        commenterProfile: 'sun',
        subject: 'Desmond the Moon Bear',
        replyTo: 'nf7nOek7uIaaQWj3',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        content: 'I love Desmond the Moon Bear!',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'jf7W3naQaOeIn7uk',
        memberId: '605038b55e6e8834ebceb5f5',
        commenterName: 'Selem',
        commenterProfile: 'sloth',
        subject: 'Desmond the Moon Bear',
        replyTo: 'ek7I3nWun7jafQOa',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        content: 'You love anything about bears.',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'Ia7n7OWnfkjeua3Q',
        memberId: '605039365e6e8834ebceb5f7',
        commenterName: 'Sefinaz',
        commenterProfile: 'sun',
        subject: 'Desmond the Moon Bear',
        replyTo: 'jf7W3naQaOeIn7uk',
        replyToOrigin: '7eO3Wan7jaIfukQn',
        content: 'Who doesn\'t like all things bears?',
        created: '07 MAY 2021',
        color: '#f7f7ff',
        border: '#d7d7dd',
    }, {
        // _id: 'eaOuIja77WkQf3nn',
        memberId: '605031675e6e8834ebceb5f2',
        commenterName: 'Amanda the Panda',
        commenterProfile: 'panda',
        subject: 'Goodies',
        content: 'I\'m making a list of snacks to bring to next club meeting.',
        created: '07 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'O7I7ujanQ3knaefW',
        memberId: '605039765e6e8834ebceb5f8',
        commenterName: 'Kermit the Kermode',
        commenterProfile: 'kermode',
        replyTo: 'eaOuIja77WkQf3nn',
        replyToOrigin: 'eaOuIja77WkQf3nn',
        subject: 'Goodies',
        content: 'Bears are all about food. I\'ll bring a chewed up salmon!',
        created: '07 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    },
]
