module.exports = [
    {
        // _id: 'QIWOejnaknafu377',
        memberId: '6071290a0a23f585405d87e4',
        name: 'Melkor',
        profile: 'melkor',
        subject: 'Welcome',
        content: 'After many millennia, I have escaped the void and I am back in Middle Earth to rule over this book club.',
        createdOn: '15 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'QnaOnafeuj7kI3W7',
        memberId: '6071290a0a23f585405d87e6',
        name: 'Jack',
        profile: 'jack',
        subject: 'Welcome',
        content: 'Did you finish the rum?',
        replyTo: 'uWa3If7anOnj7Qke',
        replyToOrigin: 'uWa3If7anOnj7Qke',
        createdOn: '15 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, 
]
