module.exports = [
    {
        // _id: 'QIWOejnaknafu377',
        memberId: '607114bee688ab3770b25929',
        name: 'Einstein',
        profile: 'einstein',
        subject: 'Welcome to Infinite Series',
        content: 'Not everything that counts can be counted. Not everything that can be counted counts.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'uWa3If7anOnj7Qke',
        memberId: '607114bee688ab3770b25922',
        name: 'Izzy',
        profile: 'izzy',
        subject: 'Welcome to Infinite Series',
        content: 'Every time I count an apple it vanishes into my tummy.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'QIWOejnaknafu377',
        memberId: '607114bee688ab3770b25929',
        name: 'Einstein',
        profile: 'einstein',
        subject: 'Welcome to Infinite Series',
        content: 'So far as the theories of mathematics are about reality, they are not certain; so far as they are certain, they are not about reality.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'uWa3If7anOnj7Qke',
        memberId: '607114bee688ab3770b25922',
        name: 'Izzy',
        profile: 'izzy',
        subject: 'Welcome to Infinite Series',
        content: 'The only certainty is jello taste good.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'QIWOejnaknafu377',
        memberId: '607114bee688ab3770b25929',
        name: 'Einstein',
        profile: 'einstein',
        subject: 'Welcome to Infinite Series',
        content: 'Once we accept our limits, we go beyond them.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    }, {
        // _id: 'uWa3If7anOnj7Qke',
        memberId: '607114bee688ab3770b25922',
        name: 'Izzy',
        profile: 'izzy',
        subject: 'Welcome to Infinite Series',
        content: 'Being a bear is about living on the limits. I push the limit on how long I can sleep all the time. I push the limit on how much tasty fruit can fit in my tummy all the time.',
        createdOn: '13 MAY 2021',
        color: '#fff7f7',
        border: '#ddd7d7',
    },  
]
